### ISSUE TITLE
Organizar os gráficos dos partidos.

### ISSUE THREAD

**Issue by dandaramcsousa** [mari-linhares/nao-nasci-pra-ser-a-outra#26]
Falta arrumar as legendas para ficarem responsíveis também.

**Comment by italo-batista** [comment]
Acho que uma boa opção é colocar o nome do partido como label na própria barra (o nome precisaria estar inclinado verticalmente).

**Comment by paul0vinicius** [comment]
Gente, tudo certo! A legenda agora está responsiva e legível. O commit está em https://github.com/mari-linhares/nao-nasci-pra-ser-a-outra/commit/d74c89946451927d4037c899606ddd2c2495fa99
